codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "50...80"

  status:
    project:
      default:
        threshold: 0.5
    patch: no
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no

ignore:
  - "vendor"
  - "cmd"
  - "sqlchain/observer"
  - "sqlchain/adapter"
  - "test"
  - "crypto/secp256k1"
  - "_example/**/*"
