package types

// Code generated by github.com/CovenantSQL/HashStablePack DO NOT EDIT.

import (
	"bytes"
	"crypto/rand"
	"encoding/binary"
	"testing"
)

func TestMarshalHash83c556Header(t *testing.T) {
	v := Header{}
	binary.Read(rand.Reader, binary.BigEndian, &v)
	bts1, err := v.MarshalHash83c556()
	if err != nil {
		t.Fatal(err)
	}
	bts2, err := v.MarshalHash83c556()
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(bts1, bts2) {
		t.Fatal("hash not stable")
	}
}

func BenchmarkMarshalHash83c556Header(b *testing.B) {
	v := Header{}
	b.ReportAllocs()
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		v.MarshalHash83c556()
	}
}

func BenchmarkAppendMsg83c556Header(b *testing.B) {
	v := Header{}
	bts := make([]byte, 0, v.Msgsize83c556())
	bts, _ = v.MarshalHash83c556()
	b.SetBytes(int64(len(bts)))
	b.ReportAllocs()
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		bts, _ = v.MarshalHash83c556()
	}
}
