// Code generated by protoc-gen-go. DO NOT EDIT.
// source: worker_types.proto

package types

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type QueryType int32

const (
	QueryType_READ  QueryType = 0
	QueryType_WRITE QueryType = 1
)

var QueryType_name = map[int32]string{
	0: "READ",
	1: "WRITE",
}
var QueryType_value = map[string]int32{
	"READ":  0,
	"WRITE": 1,
}

func (x QueryType) String() string {
	return proto.EnumName(QueryType_name, int32(x))
}
func (QueryType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_worker_types_83eaaa539d5c6e3d, []int{0}
}

type QueryRequestPayload struct {
	Queries              []string `protobuf:"bytes,1,rep,name=Queries,proto3" json:"Queries,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryRequestPayload) Reset()         { *m = QueryRequestPayload{} }
func (m *QueryRequestPayload) String() string { return proto.CompactTextString(m) }
func (*QueryRequestPayload) ProtoMessage()    {}
func (*QueryRequestPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_worker_types_83eaaa539d5c6e3d, []int{0}
}
func (m *QueryRequestPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryRequestPayload.Unmarshal(m, b)
}
func (m *QueryRequestPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryRequestPayload.Marshal(b, m, deterministic)
}
func (dst *QueryRequestPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRequestPayload.Merge(dst, src)
}
func (m *QueryRequestPayload) XXX_Size() int {
	return xxx_messageInfo_QueryRequestPayload.Size(m)
}
func (m *QueryRequestPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRequestPayload.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRequestPayload proto.InternalMessageInfo

func (m *QueryRequestPayload) GetQueries() []string {
	if m != nil {
		return m.Queries
	}
	return nil
}

type QueryRequestHeader struct {
	QueryType            QueryType `protobuf:"varint,2,opt,name=QueryType,proto3,enum=types.QueryType" json:"QueryType,omitempty"`
	NodeID               *NodeID   `protobuf:"bytes,3,opt,name=NodeID,proto3" json:"NodeID,omitempty"`
	ConnectionID         uint64    `protobuf:"varint,4,opt,name=ConnectionID,proto3" json:"ConnectionID,omitempty"`
	SeqNo                uint64    `protobuf:"varint,5,opt,name=SeqNo,proto3" json:"SeqNo,omitempty"`
	Timestamp            int64     `protobuf:"varint,6,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	BatchCount           uint64    `protobuf:"varint,7,opt,name=BatchCount,proto3" json:"BatchCount,omitempty"`
	QueriesHash          *Hash     `protobuf:"bytes,8,opt,name=QueriesHash,proto3" json:"QueriesHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *QueryRequestHeader) Reset()         { *m = QueryRequestHeader{} }
func (m *QueryRequestHeader) String() string { return proto.CompactTextString(m) }
func (*QueryRequestHeader) ProtoMessage()    {}
func (*QueryRequestHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_worker_types_83eaaa539d5c6e3d, []int{1}
}
func (m *QueryRequestHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryRequestHeader.Unmarshal(m, b)
}
func (m *QueryRequestHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryRequestHeader.Marshal(b, m, deterministic)
}
func (dst *QueryRequestHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRequestHeader.Merge(dst, src)
}
func (m *QueryRequestHeader) XXX_Size() int {
	return xxx_messageInfo_QueryRequestHeader.Size(m)
}
func (m *QueryRequestHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRequestHeader.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRequestHeader proto.InternalMessageInfo

func (m *QueryRequestHeader) GetQueryType() QueryType {
	if m != nil {
		return m.QueryType
	}
	return QueryType_READ
}

func (m *QueryRequestHeader) GetNodeID() *NodeID {
	if m != nil {
		return m.NodeID
	}
	return nil
}

func (m *QueryRequestHeader) GetConnectionID() uint64 {
	if m != nil {
		return m.ConnectionID
	}
	return 0
}

func (m *QueryRequestHeader) GetSeqNo() uint64 {
	if m != nil {
		return m.SeqNo
	}
	return 0
}

func (m *QueryRequestHeader) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *QueryRequestHeader) GetBatchCount() uint64 {
	if m != nil {
		return m.BatchCount
	}
	return 0
}

func (m *QueryRequestHeader) GetQueriesHash() *Hash {
	if m != nil {
		return m.QueriesHash
	}
	return nil
}

type SignedQueryRequestHeader struct {
	Header               *QueryRequestHeader `protobuf:"bytes,1,opt,name=Header,proto3" json:"Header,omitempty"`
	HeaderHash           *Hash               `protobuf:"bytes,2,opt,name=HeaderHash,proto3" json:"HeaderHash,omitempty"`
	Signee               *PublicKey          `protobuf:"bytes,3,opt,name=Signee,proto3" json:"Signee,omitempty"`
	Signature            *Signature          `protobuf:"bytes,4,opt,name=Signature,proto3" json:"Signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *SignedQueryRequestHeader) Reset()         { *m = SignedQueryRequestHeader{} }
func (m *SignedQueryRequestHeader) String() string { return proto.CompactTextString(m) }
func (*SignedQueryRequestHeader) ProtoMessage()    {}
func (*SignedQueryRequestHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_worker_types_83eaaa539d5c6e3d, []int{2}
}
func (m *SignedQueryRequestHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignedQueryRequestHeader.Unmarshal(m, b)
}
func (m *SignedQueryRequestHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignedQueryRequestHeader.Marshal(b, m, deterministic)
}
func (dst *SignedQueryRequestHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedQueryRequestHeader.Merge(dst, src)
}
func (m *SignedQueryRequestHeader) XXX_Size() int {
	return xxx_messageInfo_SignedQueryRequestHeader.Size(m)
}
func (m *SignedQueryRequestHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedQueryRequestHeader.DiscardUnknown(m)
}

var xxx_messageInfo_SignedQueryRequestHeader proto.InternalMessageInfo

func (m *SignedQueryRequestHeader) GetHeader() *QueryRequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *SignedQueryRequestHeader) GetHeaderHash() *Hash {
	if m != nil {
		return m.HeaderHash
	}
	return nil
}

func (m *SignedQueryRequestHeader) GetSignee() *PublicKey {
	if m != nil {
		return m.Signee
	}
	return nil
}

func (m *SignedQueryRequestHeader) GetSignature() *Signature {
	if m != nil {
		return m.Signature
	}
	return nil
}

type QueryRequest struct {
	Header               *SignedQueryRequestHeader `protobuf:"bytes,1,opt,name=Header,proto3" json:"Header,omitempty"`
	Payload              *QueryRequestPayload      `protobuf:"bytes,2,opt,name=Payload,proto3" json:"Payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *QueryRequest) Reset()         { *m = QueryRequest{} }
func (m *QueryRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRequest) ProtoMessage()    {}
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_worker_types_83eaaa539d5c6e3d, []int{3}
}
func (m *QueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryRequest.Unmarshal(m, b)
}
func (m *QueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryRequest.Marshal(b, m, deterministic)
}
func (dst *QueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRequest.Merge(dst, src)
}
func (m *QueryRequest) XXX_Size() int {
	return xxx_messageInfo_QueryRequest.Size(m)
}
func (m *QueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRequest proto.InternalMessageInfo

func (m *QueryRequest) GetHeader() *SignedQueryRequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *QueryRequest) GetPayload() *QueryRequestPayload {
	if m != nil {
		return m.Payload
	}
	return nil
}

type QueryResponseRow struct {
	Values               [][]byte `protobuf:"bytes,1,rep,name=Values,proto3" json:"Values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryResponseRow) Reset()         { *m = QueryResponseRow{} }
func (m *QueryResponseRow) String() string { return proto.CompactTextString(m) }
func (*QueryResponseRow) ProtoMessage()    {}
func (*QueryResponseRow) Descriptor() ([]byte, []int) {
	return fileDescriptor_worker_types_83eaaa539d5c6e3d, []int{4}
}
func (m *QueryResponseRow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryResponseRow.Unmarshal(m, b)
}
func (m *QueryResponseRow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryResponseRow.Marshal(b, m, deterministic)
}
func (dst *QueryResponseRow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryResponseRow.Merge(dst, src)
}
func (m *QueryResponseRow) XXX_Size() int {
	return xxx_messageInfo_QueryResponseRow.Size(m)
}
func (m *QueryResponseRow) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryResponseRow.DiscardUnknown(m)
}

var xxx_messageInfo_QueryResponseRow proto.InternalMessageInfo

func (m *QueryResponseRow) GetValues() [][]byte {
	if m != nil {
		return m.Values
	}
	return nil
}

type QueryResponsePayload struct {
	Columns              []string            `protobuf:"bytes,1,rep,name=Columns,proto3" json:"Columns,omitempty"`
	Rows                 []*QueryResponseRow `protobuf:"bytes,2,rep,name=Rows,proto3" json:"Rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *QueryResponsePayload) Reset()         { *m = QueryResponsePayload{} }
func (m *QueryResponsePayload) String() string { return proto.CompactTextString(m) }
func (*QueryResponsePayload) ProtoMessage()    {}
func (*QueryResponsePayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_worker_types_83eaaa539d5c6e3d, []int{5}
}
func (m *QueryResponsePayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryResponsePayload.Unmarshal(m, b)
}
func (m *QueryResponsePayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryResponsePayload.Marshal(b, m, deterministic)
}
func (dst *QueryResponsePayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryResponsePayload.Merge(dst, src)
}
func (m *QueryResponsePayload) XXX_Size() int {
	return xxx_messageInfo_QueryResponsePayload.Size(m)
}
func (m *QueryResponsePayload) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryResponsePayload.DiscardUnknown(m)
}

var xxx_messageInfo_QueryResponsePayload proto.InternalMessageInfo

func (m *QueryResponsePayload) GetColumns() []string {
	if m != nil {
		return m.Columns
	}
	return nil
}

func (m *QueryResponsePayload) GetRows() []*QueryResponseRow {
	if m != nil {
		return m.Rows
	}
	return nil
}

type QueryResponseHeader struct {
	Request              *SignedQueryRequestHeader `protobuf:"bytes,1,opt,name=Request,proto3" json:"Request,omitempty"`
	NodeID               *NodeID                   `protobuf:"bytes,2,opt,name=NodeID,proto3" json:"NodeID,omitempty"`
	Timestamp            int64                     `protobuf:"varint,3,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	RowCount             uint64                    `protobuf:"varint,4,opt,name=RowCount,proto3" json:"RowCount,omitempty"`
	AffectedRowsCount    uint64                    `protobuf:"varint,5,opt,name=AffectedRowsCount,proto3" json:"AffectedRowsCount,omitempty"`
	DataHash             *Hash                     `protobuf:"bytes,6,opt,name=DataHash,proto3" json:"DataHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *QueryResponseHeader) Reset()         { *m = QueryResponseHeader{} }
func (m *QueryResponseHeader) String() string { return proto.CompactTextString(m) }
func (*QueryResponseHeader) ProtoMessage()    {}
func (*QueryResponseHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_worker_types_83eaaa539d5c6e3d, []int{6}
}
func (m *QueryResponseHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryResponseHeader.Unmarshal(m, b)
}
func (m *QueryResponseHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryResponseHeader.Marshal(b, m, deterministic)
}
func (dst *QueryResponseHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryResponseHeader.Merge(dst, src)
}
func (m *QueryResponseHeader) XXX_Size() int {
	return xxx_messageInfo_QueryResponseHeader.Size(m)
}
func (m *QueryResponseHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryResponseHeader.DiscardUnknown(m)
}

var xxx_messageInfo_QueryResponseHeader proto.InternalMessageInfo

func (m *QueryResponseHeader) GetRequest() *SignedQueryRequestHeader {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *QueryResponseHeader) GetNodeID() *NodeID {
	if m != nil {
		return m.NodeID
	}
	return nil
}

func (m *QueryResponseHeader) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *QueryResponseHeader) GetRowCount() uint64 {
	if m != nil {
		return m.RowCount
	}
	return 0
}

func (m *QueryResponseHeader) GetAffectedRowsCount() uint64 {
	if m != nil {
		return m.AffectedRowsCount
	}
	return 0
}

func (m *QueryResponseHeader) GetDataHash() *Hash {
	if m != nil {
		return m.DataHash
	}
	return nil
}

type SignedQueryResponseHeader struct {
	Header               *QueryResponseHeader `protobuf:"bytes,1,opt,name=Header,proto3" json:"Header,omitempty"`
	HeaderHash           *Hash                `protobuf:"bytes,2,opt,name=HeaderHash,proto3" json:"HeaderHash,omitempty"`
	Signee               *PublicKey           `protobuf:"bytes,3,opt,name=Signee,proto3" json:"Signee,omitempty"`
	Signature            *Signature           `protobuf:"bytes,4,opt,name=Signature,proto3" json:"Signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SignedQueryResponseHeader) Reset()         { *m = SignedQueryResponseHeader{} }
func (m *SignedQueryResponseHeader) String() string { return proto.CompactTextString(m) }
func (*SignedQueryResponseHeader) ProtoMessage()    {}
func (*SignedQueryResponseHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_worker_types_83eaaa539d5c6e3d, []int{7}
}
func (m *SignedQueryResponseHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignedQueryResponseHeader.Unmarshal(m, b)
}
func (m *SignedQueryResponseHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignedQueryResponseHeader.Marshal(b, m, deterministic)
}
func (dst *SignedQueryResponseHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedQueryResponseHeader.Merge(dst, src)
}
func (m *SignedQueryResponseHeader) XXX_Size() int {
	return xxx_messageInfo_SignedQueryResponseHeader.Size(m)
}
func (m *SignedQueryResponseHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedQueryResponseHeader.DiscardUnknown(m)
}

var xxx_messageInfo_SignedQueryResponseHeader proto.InternalMessageInfo

func (m *SignedQueryResponseHeader) GetHeader() *QueryResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *SignedQueryResponseHeader) GetHeaderHash() *Hash {
	if m != nil {
		return m.HeaderHash
	}
	return nil
}

func (m *SignedQueryResponseHeader) GetSignee() *PublicKey {
	if m != nil {
		return m.Signee
	}
	return nil
}

func (m *SignedQueryResponseHeader) GetSignature() *Signature {
	if m != nil {
		return m.Signature
	}
	return nil
}

type QueryResponse struct {
	Header               *SignedQueryResponseHeader `protobuf:"bytes,1,opt,name=Header,proto3" json:"Header,omitempty"`
	Payload              *QueryResponsePayload      `protobuf:"bytes,2,opt,name=Payload,proto3" json:"Payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *QueryResponse) Reset()         { *m = QueryResponse{} }
func (m *QueryResponse) String() string { return proto.CompactTextString(m) }
func (*QueryResponse) ProtoMessage()    {}
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_worker_types_83eaaa539d5c6e3d, []int{8}
}
func (m *QueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryResponse.Unmarshal(m, b)
}
func (m *QueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryResponse.Marshal(b, m, deterministic)
}
func (dst *QueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryResponse.Merge(dst, src)
}
func (m *QueryResponse) XXX_Size() int {
	return xxx_messageInfo_QueryResponse.Size(m)
}
func (m *QueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryResponse proto.InternalMessageInfo

func (m *QueryResponse) GetHeader() *SignedQueryResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *QueryResponse) GetPayload() *QueryResponsePayload {
	if m != nil {
		return m.Payload
	}
	return nil
}

type QueryAckHeader struct {
	Response             *SignedQueryResponseHeader `protobuf:"bytes,1,opt,name=Response,proto3" json:"Response,omitempty"`
	NodeID               *NodeID                    `protobuf:"bytes,2,opt,name=NodeID,proto3" json:"NodeID,omitempty"`
	Timestamp            int64                      `protobuf:"varint,3,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *QueryAckHeader) Reset()         { *m = QueryAckHeader{} }
func (m *QueryAckHeader) String() string { return proto.CompactTextString(m) }
func (*QueryAckHeader) ProtoMessage()    {}
func (*QueryAckHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_worker_types_83eaaa539d5c6e3d, []int{9}
}
func (m *QueryAckHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryAckHeader.Unmarshal(m, b)
}
func (m *QueryAckHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryAckHeader.Marshal(b, m, deterministic)
}
func (dst *QueryAckHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAckHeader.Merge(dst, src)
}
func (m *QueryAckHeader) XXX_Size() int {
	return xxx_messageInfo_QueryAckHeader.Size(m)
}
func (m *QueryAckHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAckHeader.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAckHeader proto.InternalMessageInfo

func (m *QueryAckHeader) GetResponse() *SignedQueryResponseHeader {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *QueryAckHeader) GetNodeID() *NodeID {
	if m != nil {
		return m.NodeID
	}
	return nil
}

func (m *QueryAckHeader) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type SignedQueryAckHeader struct {
	Header               *QueryAckHeader `protobuf:"bytes,1,opt,name=Header,proto3" json:"Header,omitempty"`
	HeaderHash           *Hash           `protobuf:"bytes,2,opt,name=HeaderHash,proto3" json:"HeaderHash,omitempty"`
	Signee               *PublicKey      `protobuf:"bytes,3,opt,name=Signee,proto3" json:"Signee,omitempty"`
	Signature            *Signature      `protobuf:"bytes,4,opt,name=Signature,proto3" json:"Signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SignedQueryAckHeader) Reset()         { *m = SignedQueryAckHeader{} }
func (m *SignedQueryAckHeader) String() string { return proto.CompactTextString(m) }
func (*SignedQueryAckHeader) ProtoMessage()    {}
func (*SignedQueryAckHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_worker_types_83eaaa539d5c6e3d, []int{10}
}
func (m *SignedQueryAckHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignedQueryAckHeader.Unmarshal(m, b)
}
func (m *SignedQueryAckHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignedQueryAckHeader.Marshal(b, m, deterministic)
}
func (dst *SignedQueryAckHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedQueryAckHeader.Merge(dst, src)
}
func (m *SignedQueryAckHeader) XXX_Size() int {
	return xxx_messageInfo_SignedQueryAckHeader.Size(m)
}
func (m *SignedQueryAckHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedQueryAckHeader.DiscardUnknown(m)
}

var xxx_messageInfo_SignedQueryAckHeader proto.InternalMessageInfo

func (m *SignedQueryAckHeader) GetHeader() *QueryAckHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *SignedQueryAckHeader) GetHeaderHash() *Hash {
	if m != nil {
		return m.HeaderHash
	}
	return nil
}

func (m *SignedQueryAckHeader) GetSignee() *PublicKey {
	if m != nil {
		return m.Signee
	}
	return nil
}

func (m *SignedQueryAckHeader) GetSignature() *Signature {
	if m != nil {
		return m.Signature
	}
	return nil
}

type QueryAck struct {
	Header               *SignedQueryAckHeader `protobuf:"bytes,1,opt,name=Header,proto3" json:"Header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *QueryAck) Reset()         { *m = QueryAck{} }
func (m *QueryAck) String() string { return proto.CompactTextString(m) }
func (*QueryAck) ProtoMessage()    {}
func (*QueryAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_worker_types_83eaaa539d5c6e3d, []int{11}
}
func (m *QueryAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryAck.Unmarshal(m, b)
}
func (m *QueryAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryAck.Marshal(b, m, deterministic)
}
func (dst *QueryAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAck.Merge(dst, src)
}
func (m *QueryAck) XXX_Size() int {
	return xxx_messageInfo_QueryAck.Size(m)
}
func (m *QueryAck) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAck.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAck proto.InternalMessageInfo

func (m *QueryAck) GetHeader() *SignedQueryAckHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type NoQueryAckReportHeader struct {
	NodeID               *NodeID                    `protobuf:"bytes,1,opt,name=NodeID,proto3" json:"NodeID,omitempty"`
	Timestamp            int64                      `protobuf:"varint,2,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Request              *SignedQueryRequestHeader  `protobuf:"bytes,3,opt,name=Request,proto3" json:"Request,omitempty"`
	Response             *SignedQueryResponseHeader `protobuf:"bytes,4,opt,name=Response,proto3" json:"Response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *NoQueryAckReportHeader) Reset()         { *m = NoQueryAckReportHeader{} }
func (m *NoQueryAckReportHeader) String() string { return proto.CompactTextString(m) }
func (*NoQueryAckReportHeader) ProtoMessage()    {}
func (*NoQueryAckReportHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_worker_types_83eaaa539d5c6e3d, []int{12}
}
func (m *NoQueryAckReportHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NoQueryAckReportHeader.Unmarshal(m, b)
}
func (m *NoQueryAckReportHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NoQueryAckReportHeader.Marshal(b, m, deterministic)
}
func (dst *NoQueryAckReportHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoQueryAckReportHeader.Merge(dst, src)
}
func (m *NoQueryAckReportHeader) XXX_Size() int {
	return xxx_messageInfo_NoQueryAckReportHeader.Size(m)
}
func (m *NoQueryAckReportHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_NoQueryAckReportHeader.DiscardUnknown(m)
}

var xxx_messageInfo_NoQueryAckReportHeader proto.InternalMessageInfo

func (m *NoQueryAckReportHeader) GetNodeID() *NodeID {
	if m != nil {
		return m.NodeID
	}
	return nil
}

func (m *NoQueryAckReportHeader) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *NoQueryAckReportHeader) GetRequest() *SignedQueryRequestHeader {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *NoQueryAckReportHeader) GetResponse() *SignedQueryResponseHeader {
	if m != nil {
		return m.Response
	}
	return nil
}

type SignedNoQueryAckReportHeader struct {
	Header               *NoQueryAckReportHeader `protobuf:"bytes,1,opt,name=Header,proto3" json:"Header,omitempty"`
	HeaderHash           *Hash                   `protobuf:"bytes,2,opt,name=HeaderHash,proto3" json:"HeaderHash,omitempty"`
	Signee               *PublicKey              `protobuf:"bytes,3,opt,name=Signee,proto3" json:"Signee,omitempty"`
	Signature            *Signature              `protobuf:"bytes,4,opt,name=Signature,proto3" json:"Signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *SignedNoQueryAckReportHeader) Reset()         { *m = SignedNoQueryAckReportHeader{} }
func (m *SignedNoQueryAckReportHeader) String() string { return proto.CompactTextString(m) }
func (*SignedNoQueryAckReportHeader) ProtoMessage()    {}
func (*SignedNoQueryAckReportHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_worker_types_83eaaa539d5c6e3d, []int{13}
}
func (m *SignedNoQueryAckReportHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignedNoQueryAckReportHeader.Unmarshal(m, b)
}
func (m *SignedNoQueryAckReportHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignedNoQueryAckReportHeader.Marshal(b, m, deterministic)
}
func (dst *SignedNoQueryAckReportHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedNoQueryAckReportHeader.Merge(dst, src)
}
func (m *SignedNoQueryAckReportHeader) XXX_Size() int {
	return xxx_messageInfo_SignedNoQueryAckReportHeader.Size(m)
}
func (m *SignedNoQueryAckReportHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedNoQueryAckReportHeader.DiscardUnknown(m)
}

var xxx_messageInfo_SignedNoQueryAckReportHeader proto.InternalMessageInfo

func (m *SignedNoQueryAckReportHeader) GetHeader() *NoQueryAckReportHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *SignedNoQueryAckReportHeader) GetHeaderHash() *Hash {
	if m != nil {
		return m.HeaderHash
	}
	return nil
}

func (m *SignedNoQueryAckReportHeader) GetSignee() *PublicKey {
	if m != nil {
		return m.Signee
	}
	return nil
}

func (m *SignedNoQueryAckReportHeader) GetSignature() *Signature {
	if m != nil {
		return m.Signature
	}
	return nil
}

type NoQueryAckReport struct {
	Header               *SignedNoQueryAckReportHeader `protobuf:"bytes,1,opt,name=Header,proto3" json:"Header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *NoQueryAckReport) Reset()         { *m = NoQueryAckReport{} }
func (m *NoQueryAckReport) String() string { return proto.CompactTextString(m) }
func (*NoQueryAckReport) ProtoMessage()    {}
func (*NoQueryAckReport) Descriptor() ([]byte, []int) {
	return fileDescriptor_worker_types_83eaaa539d5c6e3d, []int{14}
}
func (m *NoQueryAckReport) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NoQueryAckReport.Unmarshal(m, b)
}
func (m *NoQueryAckReport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NoQueryAckReport.Marshal(b, m, deterministic)
}
func (dst *NoQueryAckReport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoQueryAckReport.Merge(dst, src)
}
func (m *NoQueryAckReport) XXX_Size() int {
	return xxx_messageInfo_NoQueryAckReport.Size(m)
}
func (m *NoQueryAckReport) XXX_DiscardUnknown() {
	xxx_messageInfo_NoQueryAckReport.DiscardUnknown(m)
}

var xxx_messageInfo_NoQueryAckReport proto.InternalMessageInfo

func (m *NoQueryAckReport) GetHeader() *SignedNoQueryAckReportHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type AggrNoQueryAckReportHeader struct {
	NodeID               *NodeID                         `protobuf:"bytes,1,opt,name=NodeID,proto3" json:"NodeID,omitempty"`
	Timestamp            int64                           `protobuf:"varint,2,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Request              *SignedQueryRequestHeader       `protobuf:"bytes,3,opt,name=Request,proto3" json:"Request,omitempty"`
	Reports              []*SignedNoQueryAckReportHeader `protobuf:"bytes,4,rep,name=Reports,proto3" json:"Reports,omitempty"`
	Peers                []byte                          `protobuf:"bytes,5,opt,name=Peers,proto3" json:"Peers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *AggrNoQueryAckReportHeader) Reset()         { *m = AggrNoQueryAckReportHeader{} }
func (m *AggrNoQueryAckReportHeader) String() string { return proto.CompactTextString(m) }
func (*AggrNoQueryAckReportHeader) ProtoMessage()    {}
func (*AggrNoQueryAckReportHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_worker_types_83eaaa539d5c6e3d, []int{15}
}
func (m *AggrNoQueryAckReportHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AggrNoQueryAckReportHeader.Unmarshal(m, b)
}
func (m *AggrNoQueryAckReportHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AggrNoQueryAckReportHeader.Marshal(b, m, deterministic)
}
func (dst *AggrNoQueryAckReportHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AggrNoQueryAckReportHeader.Merge(dst, src)
}
func (m *AggrNoQueryAckReportHeader) XXX_Size() int {
	return xxx_messageInfo_AggrNoQueryAckReportHeader.Size(m)
}
func (m *AggrNoQueryAckReportHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_AggrNoQueryAckReportHeader.DiscardUnknown(m)
}

var xxx_messageInfo_AggrNoQueryAckReportHeader proto.InternalMessageInfo

func (m *AggrNoQueryAckReportHeader) GetNodeID() *NodeID {
	if m != nil {
		return m.NodeID
	}
	return nil
}

func (m *AggrNoQueryAckReportHeader) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *AggrNoQueryAckReportHeader) GetRequest() *SignedQueryRequestHeader {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *AggrNoQueryAckReportHeader) GetReports() []*SignedNoQueryAckReportHeader {
	if m != nil {
		return m.Reports
	}
	return nil
}

func (m *AggrNoQueryAckReportHeader) GetPeers() []byte {
	if m != nil {
		return m.Peers
	}
	return nil
}

type SignedAggrNoQueryAckReportHeader struct {
	Header               *SignedAggrNoQueryAckReportHeader `protobuf:"bytes,1,opt,name=Header,proto3" json:"Header,omitempty"`
	HeaderHash           *Hash                             `protobuf:"bytes,2,opt,name=HeaderHash,proto3" json:"HeaderHash,omitempty"`
	Signee               *PublicKey                        `protobuf:"bytes,3,opt,name=Signee,proto3" json:"Signee,omitempty"`
	Signature            *Signature                        `protobuf:"bytes,4,opt,name=Signature,proto3" json:"Signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *SignedAggrNoQueryAckReportHeader) Reset()         { *m = SignedAggrNoQueryAckReportHeader{} }
func (m *SignedAggrNoQueryAckReportHeader) String() string { return proto.CompactTextString(m) }
func (*SignedAggrNoQueryAckReportHeader) ProtoMessage()    {}
func (*SignedAggrNoQueryAckReportHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_worker_types_83eaaa539d5c6e3d, []int{16}
}
func (m *SignedAggrNoQueryAckReportHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignedAggrNoQueryAckReportHeader.Unmarshal(m, b)
}
func (m *SignedAggrNoQueryAckReportHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignedAggrNoQueryAckReportHeader.Marshal(b, m, deterministic)
}
func (dst *SignedAggrNoQueryAckReportHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedAggrNoQueryAckReportHeader.Merge(dst, src)
}
func (m *SignedAggrNoQueryAckReportHeader) XXX_Size() int {
	return xxx_messageInfo_SignedAggrNoQueryAckReportHeader.Size(m)
}
func (m *SignedAggrNoQueryAckReportHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedAggrNoQueryAckReportHeader.DiscardUnknown(m)
}

var xxx_messageInfo_SignedAggrNoQueryAckReportHeader proto.InternalMessageInfo

func (m *SignedAggrNoQueryAckReportHeader) GetHeader() *SignedAggrNoQueryAckReportHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *SignedAggrNoQueryAckReportHeader) GetHeaderHash() *Hash {
	if m != nil {
		return m.HeaderHash
	}
	return nil
}

func (m *SignedAggrNoQueryAckReportHeader) GetSignee() *PublicKey {
	if m != nil {
		return m.Signee
	}
	return nil
}

func (m *SignedAggrNoQueryAckReportHeader) GetSignature() *Signature {
	if m != nil {
		return m.Signature
	}
	return nil
}

type SignedAggrNoQueryAckReport struct {
	Header               *SignedAggrNoQueryAckReportHeader `protobuf:"bytes,1,opt,name=Header,proto3" json:"Header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *SignedAggrNoQueryAckReport) Reset()         { *m = SignedAggrNoQueryAckReport{} }
func (m *SignedAggrNoQueryAckReport) String() string { return proto.CompactTextString(m) }
func (*SignedAggrNoQueryAckReport) ProtoMessage()    {}
func (*SignedAggrNoQueryAckReport) Descriptor() ([]byte, []int) {
	return fileDescriptor_worker_types_83eaaa539d5c6e3d, []int{17}
}
func (m *SignedAggrNoQueryAckReport) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignedAggrNoQueryAckReport.Unmarshal(m, b)
}
func (m *SignedAggrNoQueryAckReport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignedAggrNoQueryAckReport.Marshal(b, m, deterministic)
}
func (dst *SignedAggrNoQueryAckReport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedAggrNoQueryAckReport.Merge(dst, src)
}
func (m *SignedAggrNoQueryAckReport) XXX_Size() int {
	return xxx_messageInfo_SignedAggrNoQueryAckReport.Size(m)
}
func (m *SignedAggrNoQueryAckReport) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedAggrNoQueryAckReport.DiscardUnknown(m)
}

var xxx_messageInfo_SignedAggrNoQueryAckReport proto.InternalMessageInfo

func (m *SignedAggrNoQueryAckReport) GetHeader() *SignedAggrNoQueryAckReportHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryRequestPayload)(nil), "types.QueryRequestPayload")
	proto.RegisterType((*QueryRequestHeader)(nil), "types.QueryRequestHeader")
	proto.RegisterType((*SignedQueryRequestHeader)(nil), "types.SignedQueryRequestHeader")
	proto.RegisterType((*QueryRequest)(nil), "types.QueryRequest")
	proto.RegisterType((*QueryResponseRow)(nil), "types.QueryResponseRow")
	proto.RegisterType((*QueryResponsePayload)(nil), "types.QueryResponsePayload")
	proto.RegisterType((*QueryResponseHeader)(nil), "types.QueryResponseHeader")
	proto.RegisterType((*SignedQueryResponseHeader)(nil), "types.SignedQueryResponseHeader")
	proto.RegisterType((*QueryResponse)(nil), "types.QueryResponse")
	proto.RegisterType((*QueryAckHeader)(nil), "types.QueryAckHeader")
	proto.RegisterType((*SignedQueryAckHeader)(nil), "types.SignedQueryAckHeader")
	proto.RegisterType((*QueryAck)(nil), "types.QueryAck")
	proto.RegisterType((*NoQueryAckReportHeader)(nil), "types.NoQueryAckReportHeader")
	proto.RegisterType((*SignedNoQueryAckReportHeader)(nil), "types.SignedNoQueryAckReportHeader")
	proto.RegisterType((*NoQueryAckReport)(nil), "types.NoQueryAckReport")
	proto.RegisterType((*AggrNoQueryAckReportHeader)(nil), "types.AggrNoQueryAckReportHeader")
	proto.RegisterType((*SignedAggrNoQueryAckReportHeader)(nil), "types.SignedAggrNoQueryAckReportHeader")
	proto.RegisterType((*SignedAggrNoQueryAckReport)(nil), "types.SignedAggrNoQueryAckReport")
	proto.RegisterEnum("types.QueryType", QueryType_name, QueryType_value)
}

func init() { proto.RegisterFile("worker_types.proto", fileDescriptor_worker_types_83eaaa539d5c6e3d) }

var fileDescriptor_worker_types_83eaaa539d5c6e3d = []byte{
	// 772 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0x5f, 0x4f, 0x13, 0x4f,
	0x14, 0xfd, 0x4d, 0xff, 0x6c, 0xdb, 0xdb, 0x42, 0xfa, 0x1b, 0x11, 0x97, 0x82, 0xba, 0x59, 0x63,
	0xd8, 0x80, 0x60, 0x2c, 0x12, 0x35, 0x6a, 0x48, 0xa5, 0x24, 0x10, 0x13, 0xc4, 0x81, 0xe8, 0x13,
	0x31, 0x4b, 0x3b, 0x40, 0x43, 0xd9, 0x29, 0xfb, 0x27, 0x4d, 0x1f, 0x4c, 0x7c, 0xf4, 0x59, 0xbf,
	0x96, 0x8f, 0xc6, 0x27, 0x3f, 0x81, 0x6f, 0x7e, 0x03, 0xb3, 0xb3, 0xb3, 0xdb, 0xd9, 0xed, 0x42,
	0x4a, 0xf4, 0xa1, 0x6f, 0x3b, 0xf7, 0x9e, 0xdb, 0x7b, 0xcf, 0x99, 0x73, 0xb7, 0x0b, 0xb8, 0xcf,
	0xec, 0x33, 0x6a, 0x7f, 0x70, 0x07, 0x3d, 0xea, 0xac, 0xf6, 0x6c, 0xe6, 0x32, 0x9c, 0xe7, 0x87,
	0x5a, 0x59, 0x8a, 0xe9, 0x0f, 0xe1, 0xc6, 0x5b, 0x8f, 0xda, 0x03, 0x42, 0x2f, 0x3c, 0xea, 0xb8,
	0x7b, 0xe6, 0xa0, 0xcb, 0xcc, 0x36, 0x56, 0xa1, 0xe0, 0x87, 0x3b, 0xd4, 0x51, 0x91, 0x96, 0x35,
	0x4a, 0x24, 0x3c, 0xea, 0x5f, 0x32, 0x80, 0xe5, 0x8a, 0x6d, 0x6a, 0xb6, 0xa9, 0x8d, 0x57, 0xa1,
	0xc4, 0xa3, 0x07, 0x83, 0x1e, 0x55, 0x33, 0x1a, 0x32, 0xa6, 0xeb, 0xd5, 0xd5, 0xa0, 0x51, 0x14,
	0x27, 0x43, 0x08, 0xbe, 0x0f, 0xca, 0x2e, 0x6b, 0xd3, 0x9d, 0xa6, 0x9a, 0xd5, 0x90, 0x51, 0xae,
	0x4f, 0x09, 0x70, 0x10, 0x24, 0x22, 0x89, 0x75, 0xa8, 0x6c, 0x32, 0xcb, 0xa2, 0x2d, 0xb7, 0xc3,
	0xac, 0x9d, 0xa6, 0x9a, 0xd3, 0x90, 0x91, 0x23, 0xb1, 0x18, 0x9e, 0x81, 0xfc, 0x3e, 0xbd, 0xd8,
	0x65, 0x6a, 0x9e, 0x27, 0x83, 0x03, 0x5e, 0x80, 0xd2, 0x41, 0xe7, 0x9c, 0x3a, 0xae, 0x79, 0xde,
	0x53, 0x15, 0x0d, 0x19, 0x59, 0x32, 0x0c, 0xe0, 0x3b, 0x00, 0xaf, 0x4c, 0xb7, 0x75, 0xba, 0xc9,
	0x3c, 0xcb, 0x55, 0x0b, 0xbc, 0x50, 0x8a, 0xe0, 0x15, 0x28, 0x0b, 0xc2, 0xdb, 0xa6, 0x73, 0xaa,
	0x16, 0xf9, 0x8c, 0x65, 0x31, 0xa3, 0x1f, 0x22, 0x72, 0x5e, 0xff, 0x8e, 0x40, 0xdd, 0xef, 0x9c,
	0x58, 0xb4, 0x9d, 0x22, 0xcd, 0x23, 0x50, 0x82, 0x27, 0x15, 0xf1, 0x9f, 0x99, 0x93, 0x75, 0x89,
	0x41, 0x89, 0x00, 0xe2, 0x65, 0x80, 0xe0, 0x89, 0x77, 0xcf, 0x8c, 0x76, 0x97, 0xd2, 0xd8, 0x00,
	0x85, 0xf7, 0xa6, 0x42, 0xca, 0x50, 0xf7, 0x3d, 0xef, 0xa8, 0xdb, 0x69, 0xbd, 0xa6, 0x03, 0x22,
	0xf2, 0xfe, 0x25, 0xf9, 0x4f, 0xa6, 0xeb, 0xd9, 0x94, 0x4b, 0x39, 0x04, 0x47, 0x71, 0x32, 0x84,
	0xe8, 0x1f, 0xa1, 0x22, 0x0f, 0x89, 0x9f, 0x24, 0x98, 0xdc, 0x95, 0x8a, 0xd3, 0xa8, 0x47, 0x7c,
	0x1e, 0x43, 0x41, 0x38, 0x4b, 0x90, 0xa9, 0xa5, 0x68, 0x20, 0x10, 0x24, 0x84, 0xea, 0x4b, 0x50,
	0x15, 0x79, 0xa7, 0xc7, 0x2c, 0x87, 0x12, 0xd6, 0xc7, 0xb3, 0xa0, 0xbc, 0x33, 0xbb, 0x9e, 0xf0,
	0x65, 0x85, 0x88, 0x93, 0x7e, 0x08, 0x33, 0x31, 0xac, 0x64, 0xe4, 0x4d, 0xd6, 0xf5, 0xce, 0xad,
	0xc8, 0xc8, 0xe2, 0x88, 0x97, 0x21, 0x47, 0x58, 0xdf, 0x51, 0x33, 0x5a, 0xd6, 0x28, 0xd7, 0x6f,
	0xc5, 0x07, 0x8a, 0x1a, 0x12, 0x0e, 0xd2, 0x3f, 0x67, 0xa2, 0x3d, 0x09, 0x52, 0x82, 0xd8, 0x33,
	0x28, 0x88, 0xe9, 0xc7, 0x95, 0x24, 0xc4, 0x4b, 0x1b, 0x90, 0xb9, 0x6a, 0x03, 0x62, 0x3e, 0xce,
	0x26, 0x7d, 0x5c, 0x83, 0x22, 0x61, 0xfd, 0xc0, 0xc5, 0xc1, 0x6e, 0x44, 0x67, 0xfc, 0x00, 0xfe,
	0x6f, 0x1c, 0x1f, 0xd3, 0x96, 0x4b, 0xdb, 0x3e, 0x87, 0x00, 0x14, 0xec, 0xc8, 0x68, 0x02, 0x2f,
	0x42, 0xb1, 0x69, 0xba, 0x26, 0x37, 0x9c, 0x32, 0x6a, 0xb8, 0x28, 0xa9, 0xff, 0x40, 0x30, 0x17,
	0x63, 0x17, 0x13, 0xa4, 0x9e, 0xb0, 0x48, 0x2d, 0x4d, 0xd7, 0xc9, 0x74, 0xfb, 0x27, 0x04, 0x53,
	0xb1, 0x31, 0xf1, 0xd3, 0x04, 0x19, 0x2d, 0xed, 0x72, 0x53, 0x29, 0xad, 0x27, 0x0d, 0x3f, 0x9f,
	0xa6, 0xc3, 0x88, 0xe3, 0xbf, 0x22, 0x98, 0xe6, 0x88, 0x46, 0xeb, 0x4c, 0xfc, 0xd2, 0x0b, 0x28,
	0x86, 0xf0, 0xb1, 0xa7, 0x88, 0x2a, 0xfe, 0x89, 0xc9, 0xf4, 0x6f, 0x08, 0x66, 0xa4, 0x66, 0xc3,
	0xd9, 0x56, 0x12, 0xfa, 0xdc, 0x94, 0x49, 0x46, 0xb0, 0x49, 0xbb, 0xe7, 0x0d, 0x28, 0x86, 0x03,
	0xe2, 0xb5, 0x04, 0x83, 0xf9, 0x51, 0x6d, 0x47, 0x78, 0xf8, 0x1b, 0x30, 0xbb, 0xcb, 0xc2, 0x24,
	0xa1, 0x3d, 0x66, 0x87, 0xef, 0xfa, 0xa1, 0xde, 0x68, 0x6c, 0xbd, 0x33, 0xc9, 0xa5, 0x96, 0x5e,
	0x2a, 0xd9, 0x6b, 0xbe, 0x54, 0x64, 0xb7, 0xe4, 0xae, 0xeb, 0x16, 0xfd, 0x27, 0x82, 0x85, 0x00,
	0x77, 0x09, 0xbd, 0xf5, 0x84, 0x5c, 0xb7, 0x23, 0x7a, 0x69, 0xf0, 0x49, 0xbb, 0xf8, 0x37, 0x50,
	0x4d, 0x0e, 0x8a, 0x9f, 0x27, 0x18, 0xdd, 0x8b, 0xc9, 0x75, 0x35, 0x2f, 0xfd, 0x37, 0x82, 0x5a,
	0xe3, 0xe4, 0xc4, 0x9e, 0x50, 0x33, 0xbc, 0xf4, 0x4b, 0xfd, 0x79, 0x1c, 0x35, 0xc7, 0xff, 0xe4,
	0xc6, 0x22, 0x17, 0xd6, 0xf8, 0xdf, 0x55, 0x7b, 0x94, 0xda, 0x0e, 0xff, 0xcf, 0xa8, 0x90, 0xe0,
	0xa0, 0xff, 0x42, 0xa0, 0x05, 0xf5, 0x57, 0x30, 0xdf, 0x48, 0xa8, 0xba, 0x18, 0x6b, 0x7c, 0x79,
	0xe1, 0xa4, 0x39, 0xe6, 0x10, 0x6a, 0x97, 0x8f, 0xfc, 0xd7, 0x2c, 0x97, 0x34, 0xe9, 0xa3, 0x19,
	0x17, 0x21, 0x47, 0xb6, 0x1a, 0xcd, 0xea, 0x7f, 0xb8, 0x04, 0xf9, 0xf7, 0x64, 0xe7, 0x60, 0xab,
	0x8a, 0x8e, 0x14, 0xfe, 0x95, 0xbe, 0xf6, 0x27, 0x00, 0x00, 0xff, 0xff, 0x42, 0x89, 0xe7, 0x82,
	0xcf, 0x0b, 0x00, 0x00,
}
