// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sqlchaintypes.proto

package pbtypes

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TxType int32

const (
	TxType_QUERY   TxType = 0
	TxType_STORAGE TxType = 1
)

var TxType_name = map[int32]string{
	0: "QUERY",
	1: "STORAGE",
}
var TxType_value = map[string]int32{
	"QUERY":   0,
	"STORAGE": 1,
}

func (x TxType) String() string {
	return proto.EnumName(TxType_name, int32(x))
}
func (TxType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_sqlchaintypes_eed04090db1a5336, []int{0}
}

type Signature struct {
	R                    string   `protobuf:"bytes,1,opt,name=R" json:"R,omitempty"`
	S                    string   `protobuf:"bytes,2,opt,name=S" json:"S,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Signature) Reset()         { *m = Signature{} }
func (m *Signature) String() string { return proto.CompactTextString(m) }
func (*Signature) ProtoMessage()    {}
func (*Signature) Descriptor() ([]byte, []int) {
	return fileDescriptor_sqlchaintypes_eed04090db1a5336, []int{0}
}
func (m *Signature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Signature.Unmarshal(m, b)
}
func (m *Signature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Signature.Marshal(b, m, deterministic)
}
func (dst *Signature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Signature.Merge(dst, src)
}
func (m *Signature) XXX_Size() int {
	return xxx_messageInfo_Signature.Size(m)
}
func (m *Signature) XXX_DiscardUnknown() {
	xxx_messageInfo_Signature.DiscardUnknown(m)
}

var xxx_messageInfo_Signature proto.InternalMessageInfo

func (m *Signature) GetR() string {
	if m != nil {
		return m.R
	}
	return ""
}

func (m *Signature) GetS() string {
	if m != nil {
		return m.S
	}
	return ""
}

type PublicKey struct {
	PublicKey            []byte   `protobuf:"bytes,1,opt,name=PublicKey,proto3" json:"PublicKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublicKey) Reset()         { *m = PublicKey{} }
func (m *PublicKey) String() string { return proto.CompactTextString(m) }
func (*PublicKey) ProtoMessage()    {}
func (*PublicKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_sqlchaintypes_eed04090db1a5336, []int{1}
}
func (m *PublicKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublicKey.Unmarshal(m, b)
}
func (m *PublicKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublicKey.Marshal(b, m, deterministic)
}
func (dst *PublicKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublicKey.Merge(dst, src)
}
func (m *PublicKey) XXX_Size() int {
	return xxx_messageInfo_PublicKey.Size(m)
}
func (m *PublicKey) XXX_DiscardUnknown() {
	xxx_messageInfo_PublicKey.DiscardUnknown(m)
}

var xxx_messageInfo_PublicKey proto.InternalMessageInfo

func (m *PublicKey) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

type Hash struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=Hash,proto3" json:"Hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Hash) Reset()         { *m = Hash{} }
func (m *Hash) String() string { return proto.CompactTextString(m) }
func (*Hash) ProtoMessage()    {}
func (*Hash) Descriptor() ([]byte, []int) {
	return fileDescriptor_sqlchaintypes_eed04090db1a5336, []int{2}
}
func (m *Hash) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hash.Unmarshal(m, b)
}
func (m *Hash) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hash.Marshal(b, m, deterministic)
}
func (dst *Hash) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hash.Merge(dst, src)
}
func (m *Hash) XXX_Size() int {
	return xxx_messageInfo_Hash.Size(m)
}
func (m *Hash) XXX_DiscardUnknown() {
	xxx_messageInfo_Hash.DiscardUnknown(m)
}

var xxx_messageInfo_Hash proto.InternalMessageInfo

func (m *Hash) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type UtxoEntry struct {
	IsCoinbase           bool             `protobuf:"varint,1,opt,name=IsCoinbase" json:"IsCoinbase,omitempty"`
	FromMainChain        bool             `protobuf:"varint,2,opt,name=FromMainChain" json:"FromMainChain,omitempty"`
	BlockHeight          uint32           `protobuf:"varint,3,opt,name=BlockHeight" json:"BlockHeight,omitempty"`
	SparseOutputs        map[uint32]*Utxo `protobuf:"bytes,4,rep,name=SparseOutputs" json:"SparseOutputs,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *UtxoEntry) Reset()         { *m = UtxoEntry{} }
func (m *UtxoEntry) String() string { return proto.CompactTextString(m) }
func (*UtxoEntry) ProtoMessage()    {}
func (*UtxoEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_sqlchaintypes_eed04090db1a5336, []int{3}
}
func (m *UtxoEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UtxoEntry.Unmarshal(m, b)
}
func (m *UtxoEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UtxoEntry.Marshal(b, m, deterministic)
}
func (dst *UtxoEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UtxoEntry.Merge(dst, src)
}
func (m *UtxoEntry) XXX_Size() int {
	return xxx_messageInfo_UtxoEntry.Size(m)
}
func (m *UtxoEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_UtxoEntry.DiscardUnknown(m)
}

var xxx_messageInfo_UtxoEntry proto.InternalMessageInfo

func (m *UtxoEntry) GetIsCoinbase() bool {
	if m != nil {
		return m.IsCoinbase
	}
	return false
}

func (m *UtxoEntry) GetFromMainChain() bool {
	if m != nil {
		return m.FromMainChain
	}
	return false
}

func (m *UtxoEntry) GetBlockHeight() uint32 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *UtxoEntry) GetSparseOutputs() map[uint32]*Utxo {
	if m != nil {
		return m.SparseOutputs
	}
	return nil
}

type Utxo struct {
	UtxoHeader           *UtxoHeader `protobuf:"bytes,1,opt,name=UtxoHeader" json:"UtxoHeader,omitempty"`
	Spent                bool        `protobuf:"varint,2,opt,name=Spent" json:"Spent,omitempty"`
	Amount               uint64      `protobuf:"varint,3,opt,name=amount" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Utxo) Reset()         { *m = Utxo{} }
func (m *Utxo) String() string { return proto.CompactTextString(m) }
func (*Utxo) ProtoMessage()    {}
func (*Utxo) Descriptor() ([]byte, []int) {
	return fileDescriptor_sqlchaintypes_eed04090db1a5336, []int{4}
}
func (m *Utxo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Utxo.Unmarshal(m, b)
}
func (m *Utxo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Utxo.Marshal(b, m, deterministic)
}
func (dst *Utxo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Utxo.Merge(dst, src)
}
func (m *Utxo) XXX_Size() int {
	return xxx_messageInfo_Utxo.Size(m)
}
func (m *Utxo) XXX_DiscardUnknown() {
	xxx_messageInfo_Utxo.DiscardUnknown(m)
}

var xxx_messageInfo_Utxo proto.InternalMessageInfo

func (m *Utxo) GetUtxoHeader() *UtxoHeader {
	if m != nil {
		return m.UtxoHeader
	}
	return nil
}

func (m *Utxo) GetSpent() bool {
	if m != nil {
		return m.Spent
	}
	return false
}

func (m *Utxo) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type UtxoHeader struct {
	Version              int32      `protobuf:"varint,1,opt,name=Version" json:"Version,omitempty"`
	PrevTxHash           *Hash      `protobuf:"bytes,2,opt,name=PrevTxHash" json:"PrevTxHash,omitempty"`
	Signee               *PublicKey `protobuf:"bytes,3,opt,name=Signee" json:"Signee,omitempty"`
	Signature            *Signature `protobuf:"bytes,4,opt,name=Signature" json:"Signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UtxoHeader) Reset()         { *m = UtxoHeader{} }
func (m *UtxoHeader) String() string { return proto.CompactTextString(m) }
func (*UtxoHeader) ProtoMessage()    {}
func (*UtxoHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_sqlchaintypes_eed04090db1a5336, []int{5}
}
func (m *UtxoHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UtxoHeader.Unmarshal(m, b)
}
func (m *UtxoHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UtxoHeader.Marshal(b, m, deterministic)
}
func (dst *UtxoHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UtxoHeader.Merge(dst, src)
}
func (m *UtxoHeader) XXX_Size() int {
	return xxx_messageInfo_UtxoHeader.Size(m)
}
func (m *UtxoHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_UtxoHeader.DiscardUnknown(m)
}

var xxx_messageInfo_UtxoHeader proto.InternalMessageInfo

func (m *UtxoHeader) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *UtxoHeader) GetPrevTxHash() *Hash {
	if m != nil {
		return m.PrevTxHash
	}
	return nil
}

func (m *UtxoHeader) GetSignee() *PublicKey {
	if m != nil {
		return m.Signee
	}
	return nil
}

func (m *UtxoHeader) GetSignature() *Signature {
	if m != nil {
		return m.Signature
	}
	return nil
}

type Tx struct {
	UtxoIn               []*Utxo  `protobuf:"bytes,1,rep,name=UtxoIn" json:"UtxoIn,omitempty"`
	UtxoOut              []*Utxo  `protobuf:"bytes,2,rep,name=UtxoOut" json:"UtxoOut,omitempty"`
	Type                 TxType   `protobuf:"varint,3,opt,name=type,enum=pbtypes.TxType" json:"type,omitempty"`
	Content              string   `protobuf:"bytes,4,opt,name=Content" json:"Content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tx) Reset()         { *m = Tx{} }
func (m *Tx) String() string { return proto.CompactTextString(m) }
func (*Tx) ProtoMessage()    {}
func (*Tx) Descriptor() ([]byte, []int) {
	return fileDescriptor_sqlchaintypes_eed04090db1a5336, []int{6}
}
func (m *Tx) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tx.Unmarshal(m, b)
}
func (m *Tx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tx.Marshal(b, m, deterministic)
}
func (dst *Tx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tx.Merge(dst, src)
}
func (m *Tx) XXX_Size() int {
	return xxx_messageInfo_Tx.Size(m)
}
func (m *Tx) XXX_DiscardUnknown() {
	xxx_messageInfo_Tx.DiscardUnknown(m)
}

var xxx_messageInfo_Tx proto.InternalMessageInfo

func (m *Tx) GetUtxoIn() []*Utxo {
	if m != nil {
		return m.UtxoIn
	}
	return nil
}

func (m *Tx) GetUtxoOut() []*Utxo {
	if m != nil {
		return m.UtxoOut
	}
	return nil
}

func (m *Tx) GetType() TxType {
	if m != nil {
		return m.Type
	}
	return TxType_QUERY
}

func (m *Tx) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func init() {
	proto.RegisterType((*Signature)(nil), "pbtypes.Signature")
	proto.RegisterType((*PublicKey)(nil), "pbtypes.PublicKey")
	proto.RegisterType((*Hash)(nil), "pbtypes.Hash")
	proto.RegisterType((*UtxoEntry)(nil), "pbtypes.UtxoEntry")
	proto.RegisterMapType((map[uint32]*Utxo)(nil), "pbtypes.UtxoEntry.SparseOutputsEntry")
	proto.RegisterType((*Utxo)(nil), "pbtypes.Utxo")
	proto.RegisterType((*UtxoHeader)(nil), "pbtypes.UtxoHeader")
	proto.RegisterType((*Tx)(nil), "pbtypes.Tx")
	proto.RegisterEnum("pbtypes.TxType", TxType_name, TxType_value)
}

func init() { proto.RegisterFile("sqlchaintypes.proto", fileDescriptor_sqlchaintypes_eed04090db1a5336) }

var fileDescriptor_sqlchaintypes_eed04090db1a5336 = []byte{
	// 485 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x93, 0xd1, 0x6e, 0xd3, 0x30,
	0x14, 0x86, 0x49, 0x9b, 0xb6, 0xcb, 0xc9, 0x02, 0xd5, 0x19, 0x42, 0xd1, 0x84, 0x50, 0x94, 0x31,
	0xad, 0x4c, 0xa2, 0x42, 0xd9, 0x0d, 0xe2, 0x0e, 0xaa, 0x42, 0xa7, 0x09, 0x75, 0x9c, 0x64, 0x48,
	0x5c, 0xa6, 0xc5, 0x5a, 0xa3, 0x75, 0x76, 0x48, 0x9c, 0xa9, 0x7d, 0x0c, 0xc4, 0xa3, 0xf0, 0x82,
	0xc8, 0x4e, 0x9a, 0x25, 0x1b, 0x57, 0xf1, 0xff, 0x9f, 0xcf, 0x3d, 0xc7, 0x7f, 0x6d, 0x38, 0xc8,
	0x7f, 0xad, 0x97, 0xab, 0x38, 0xe1, 0x72, 0x9b, 0xb2, 0x7c, 0x9c, 0x66, 0x42, 0x0a, 0x1c, 0xa4,
	0x0b, 0x2d, 0xfd, 0x13, 0xb0, 0xc2, 0xe4, 0x9a, 0xc7, 0xb2, 0xc8, 0x18, 0xee, 0x83, 0x41, 0xae,
	0xe1, 0x19, 0x23, 0x8b, 0x0c, 0x52, 0x2a, 0x74, 0x3b, 0xa5, 0x0a, 0xfd, 0x37, 0x60, 0x5d, 0x16,
	0x8b, 0x75, 0xb2, 0xbc, 0x60, 0x5b, 0x7c, 0xd9, 0x10, 0x7a, 0xc3, 0x3e, 0xdd, 0x1b, 0xfe, 0x21,
	0x98, 0xb3, 0x38, 0x5f, 0x21, 0x96, 0xdf, 0x0a, 0xd0, 0x6b, 0xff, 0x77, 0x07, 0xac, 0x2b, 0xb9,
	0x11, 0x53, 0x2e, 0xb3, 0x2d, 0xbe, 0x02, 0x38, 0xcf, 0x27, 0x22, 0xe1, 0x8b, 0x38, 0x67, 0x9a,
	0xdb, 0xa3, 0x86, 0x83, 0xaf, 0xc1, 0xf9, 0x9c, 0x89, 0xdb, 0xaf, 0x71, 0xc2, 0x27, 0xea, 0x08,
	0x7a, 0x9c, 0x3d, 0x6a, 0x9b, 0xe8, 0x81, 0xfd, 0x69, 0x2d, 0x96, 0x37, 0x33, 0x96, 0x5c, 0xaf,
	0xa4, 0xdb, 0xf5, 0x8c, 0x91, 0x43, 0x4d, 0x0b, 0x2f, 0xc0, 0x09, 0xd3, 0x38, 0xcb, 0xd9, 0xbc,
	0x90, 0x69, 0x21, 0x73, 0xd7, 0xf4, 0xba, 0x23, 0x3b, 0x38, 0x1e, 0x57, 0x31, 0x8c, 0xeb, 0x91,
	0xc6, 0x2d, 0x4e, 0x5b, 0xd4, 0xde, 0x7b, 0x38, 0x07, 0x7c, 0x0c, 0xe1, 0x10, 0xba, 0x37, 0x55,
	0x18, 0x0e, 0xa9, 0x25, 0x1e, 0x41, 0xef, 0x2e, 0x5e, 0x17, 0x4c, 0x0f, 0x6d, 0x07, 0x4e, 0xab,
	0x19, 0x95, 0xb5, 0x0f, 0x9d, 0xf7, 0x86, 0x9f, 0x80, 0xa9, 0x2c, 0x3c, 0x03, 0x50, 0xdf, 0x19,
	0x8b, 0x7f, 0xb2, 0x4c, 0xff, 0x92, 0x1d, 0x1c, 0xb4, 0x76, 0x95, 0x25, 0x6a, 0x60, 0xf8, 0x1c,
	0x7a, 0x61, 0xca, 0xb8, 0xac, 0xa2, 0x29, 0x05, 0xbe, 0x80, 0x7e, 0x7c, 0x2b, 0x0a, 0x5e, 0xa6,
	0x61, 0x52, 0xa5, 0xfc, 0xbf, 0x46, 0xb3, 0x07, 0xba, 0x30, 0xf8, 0xce, 0xb2, 0x3c, 0x11, 0x5c,
	0xb7, 0xeb, 0xd1, 0x4e, 0xe2, 0x5b, 0x80, 0xcb, 0x8c, 0xdd, 0x45, 0x1b, 0xfd, 0x0f, 0x3e, 0x3c,
	0x81, 0x32, 0xa9, 0x01, 0xe0, 0x29, 0xf4, 0xd5, 0x35, 0x62, 0x4c, 0xf7, 0xb3, 0x03, 0xac, 0xd1,
	0xfa, 0x5a, 0x50, 0x45, 0xe0, 0xbb, 0xc6, 0x95, 0x73, 0xcd, 0x07, 0x78, 0x5d, 0xa1, 0x7b, 0xc8,
	0xff, 0x63, 0x40, 0x27, 0xda, 0xe0, 0x31, 0xf4, 0xd5, 0xec, 0xe7, 0x6a, 0xd8, 0xee, 0xe3, 0x44,
	0xab, 0x22, 0x9e, 0xc0, 0x40, 0xad, 0xe6, 0x85, 0xca, 0xe4, 0x3f, 0xdc, 0xae, 0x8a, 0x47, 0x60,
	0x2a, 0x5b, 0x8f, 0xfc, 0x34, 0x78, 0x56, 0x53, 0xd1, 0x26, 0xda, 0xa6, 0x8c, 0x74, 0x51, 0x45,
	0x34, 0x11, 0x5c, 0xaa, 0x84, 0x4d, 0xfd, 0x16, 0x76, 0xf2, 0xd4, 0x83, 0x7e, 0x49, 0xa2, 0x05,
	0xbd, 0x6f, 0x57, 0x53, 0xfa, 0x31, 0x7c, 0x82, 0x36, 0x0c, 0xc2, 0x68, 0x4e, 0x1f, 0xbf, 0x4c,
	0x87, 0xc6, 0xa2, 0xaf, 0x1f, 0xdb, 0xd9, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc9, 0x95, 0x65,
	0xa6, 0x83, 0x03, 0x00, 0x00,
}
