package proto

// Code generated by github.com/CovenantSQL/HashStablePack DO NOT EDIT.

import (
	"github.com/CovenantSQL/HashStablePack/msgp"
)

// MarshalHash marshals for hash
func (z *AddrAndGas) MarshalHash() (o []byte, err error) {
	var b []byte
	o = msgp.Require(b, z.Msgsize())
	// map header, size 3
	o = append(o, 0x83, 0x83)
	if oTemp, err := z.AccountAddress.MarshalHash(); err != nil {
		return nil, err
	} else {
		o = msgp.AppendBytes(o, oTemp)
	}
	// map header, size 1
	o = append(o, 0x83, 0x81, 0x81)
	if oTemp, err := z.RawNodeID.Hash.MarshalHash(); err != nil {
		return nil, err
	} else {
		o = msgp.AppendBytes(o, oTemp)
	}
	o = append(o, 0x83)
	o = msgp.AppendUint64(o, z.GasAmount)
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *AddrAndGas) Msgsize() (s int) {
	s = 1 + 15 + z.AccountAddress.Msgsize() + 10 + 1 + 5 + z.RawNodeID.Hash.Msgsize() + 10 + msgp.Uint64Size
	return
}

// MarshalHash marshals for hash
func (z *Node) MarshalHash() (o []byte, err error) {
	var b []byte
	o = msgp.Require(b, z.Msgsize())
	// map header, size 5
	o = append(o, 0x85, 0x85)
	o = msgp.AppendString(o, string(z.ID))
	o = append(o, 0x85)
	o = msgp.AppendInt(o, int(z.Role))
	o = append(o, 0x85)
	o = msgp.AppendString(o, z.Addr)
	o = append(o, 0x85)
	if z.PublicKey == nil {
		o = msgp.AppendNil(o)
	} else {
		if oTemp, err := z.PublicKey.MarshalHash(); err != nil {
			return nil, err
		} else {
			o = msgp.AppendBytes(o, oTemp)
		}
	}
	o = append(o, 0x85)
	if oTemp, err := z.Nonce.MarshalHash(); err != nil {
		return nil, err
	} else {
		o = msgp.AppendBytes(o, oTemp)
	}
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Node) Msgsize() (s int) {
	s = 1 + 3 + msgp.StringPrefixSize + len(string(z.ID)) + 5 + msgp.IntSize + 5 + msgp.StringPrefixSize + len(z.Addr) + 10
	if z.PublicKey == nil {
		s += msgp.NilSize
	} else {
		s += z.PublicKey.Msgsize()
	}
	s += 6 + z.Nonce.Msgsize()
	return
}

// MarshalHash marshals for hash
func (z NodeID) MarshalHash() (o []byte, err error) {
	var b []byte
	o = msgp.Require(b, z.Msgsize())
	o = msgp.AppendString(o, string(z))
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z NodeID) Msgsize() (s int) {
	s = msgp.StringPrefixSize + len(string(z))
	return
}

// MarshalHash marshals for hash
func (z *NodeKey) MarshalHash() (o []byte, err error) {
	var b []byte
	o = msgp.Require(b, z.Msgsize())
	// map header, size 1
	o = append(o, 0x81, 0x81)
	if oTemp, err := z.Hash.MarshalHash(); err != nil {
		return nil, err
	} else {
		o = msgp.AppendBytes(o, oTemp)
	}
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *NodeKey) Msgsize() (s int) {
	s = 1 + 5 + z.Hash.Msgsize()
	return
}

// MarshalHash marshals for hash
func (z *RawNodeID) MarshalHash() (o []byte, err error) {
	var b []byte
	o = msgp.Require(b, z.Msgsize())
	// map header, size 1
	o = append(o, 0x81, 0x81)
	if oTemp, err := z.Hash.MarshalHash(); err != nil {
		return nil, err
	} else {
		o = msgp.AppendBytes(o, oTemp)
	}
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *RawNodeID) Msgsize() (s int) {
	s = 1 + 5 + z.Hash.Msgsize()
	return
}

// MarshalHash marshals for hash
func (z ServerRole) MarshalHash() (o []byte, err error) {
	var b []byte
	o = msgp.Require(b, z.Msgsize())
	o = msgp.AppendInt(o, int(z))
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z ServerRole) Msgsize() (s int) {
	s = msgp.IntSize
	return
}

// MarshalHash marshals for hash
func (z ServerRoles) MarshalHash() (o []byte, err error) {
	var b []byte
	o = msgp.Require(b, z.Msgsize())
	o = msgp.AppendArrayHeader(o, uint32(len(z)))
	for za0001 := range z {
		o = msgp.AppendInt(o, int(z[za0001]))
	}
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z ServerRoles) Msgsize() (s int) {
	s = msgp.ArrayHeaderSize + (len(z) * (msgp.IntSize))
	return
}
