// Code generated by mockery v1.0.0. DO NOT EDIT.
package kayak

import mock "github.com/stretchr/testify/mock"

// MockConfig is an autogenerated mock type for the Config type
type MockConfig struct {
	mock.Mock
}

// GetRuntimeConfig provides a mock function with given fields:
func (_m *MockConfig) GetRuntimeConfig() *RuntimeConfig {
	ret := _m.Called()

	var r0 *RuntimeConfig
	if rf, ok := ret.Get(0).(func() *RuntimeConfig); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*RuntimeConfig)
		}
	}

	return r0
}
