package kayak

// Code generated by github.com/CovenantSQL/HashStablePack DO NOT EDIT.

import (
	"github.com/CovenantSQL/HashStablePack/msgp"
)

// MarshalHash marshals for hash
func (z *Log) MarshalHash() (o []byte, err error) {
	var b []byte
	o = msgp.Require(b, z.Msgsize())
	// map header, size 5
	o = append(o, 0x85, 0x85)
	o = msgp.AppendUint64(o, z.Index)
	o = append(o, 0x85)
	o = msgp.AppendUint64(o, z.Term)
	o = append(o, 0x85)
	o = msgp.AppendBytes(o, z.Data)
	o = append(o, 0x85)
	if z.LastHash == nil {
		o = msgp.AppendNil(o)
	} else {
		if oTemp, err := z.LastHash.MarshalHash(); err != nil {
			return nil, err
		} else {
			o = msgp.AppendBytes(o, oTemp)
		}
	}
	o = append(o, 0x85)
	if oTemp, err := z.Hash.MarshalHash(); err != nil {
		return nil, err
	} else {
		o = msgp.AppendBytes(o, oTemp)
	}
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Log) Msgsize() (s int) {
	s = 1 + 6 + msgp.Uint64Size + 5 + msgp.Uint64Size + 5 + msgp.BytesPrefixSize + len(z.Data) + 9
	if z.LastHash == nil {
		s += msgp.NilSize
	} else {
		s += z.LastHash.Msgsize()
	}
	s += 5 + z.Hash.Msgsize()
	return
}

// MarshalHash marshals for hash
func (z *Peers) MarshalHash() (o []byte, err error) {
	var b []byte
	o = msgp.Require(b, z.Msgsize())
	// map header, size 5
	o = append(o, 0x85, 0x85)
	o = msgp.AppendUint64(o, z.Term)
	o = append(o, 0x85)
	if z.Leader == nil {
		o = msgp.AppendNil(o)
	} else {
		if oTemp, err := z.Leader.MarshalHash(); err != nil {
			return nil, err
		} else {
			o = msgp.AppendBytes(o, oTemp)
		}
	}
	o = append(o, 0x85)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Servers)))
	for za0001 := range z.Servers {
		if z.Servers[za0001] == nil {
			o = msgp.AppendNil(o)
		} else {
			if oTemp, err := z.Servers[za0001].MarshalHash(); err != nil {
				return nil, err
			} else {
				o = msgp.AppendBytes(o, oTemp)
			}
		}
	}
	o = append(o, 0x85)
	if z.PubKey == nil {
		o = msgp.AppendNil(o)
	} else {
		if oTemp, err := z.PubKey.MarshalHash(); err != nil {
			return nil, err
		} else {
			o = msgp.AppendBytes(o, oTemp)
		}
	}
	o = append(o, 0x85)
	if z.Signature == nil {
		o = msgp.AppendNil(o)
	} else {
		if oTemp, err := z.Signature.MarshalHash(); err != nil {
			return nil, err
		} else {
			o = msgp.AppendBytes(o, oTemp)
		}
	}
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Peers) Msgsize() (s int) {
	s = 1 + 5 + msgp.Uint64Size + 7
	if z.Leader == nil {
		s += msgp.NilSize
	} else {
		s += z.Leader.Msgsize()
	}
	s += 8 + msgp.ArrayHeaderSize
	for za0001 := range z.Servers {
		if z.Servers[za0001] == nil {
			s += msgp.NilSize
		} else {
			s += z.Servers[za0001].Msgsize()
		}
	}
	s += 7
	if z.PubKey == nil {
		s += msgp.NilSize
	} else {
		s += z.PubKey.Msgsize()
	}
	s += 10
	if z.Signature == nil {
		s += msgp.NilSize
	} else {
		s += z.Signature.Msgsize()
	}
	return
}

// MarshalHash marshals for hash
func (z *Server) MarshalHash() (o []byte, err error) {
	var b []byte
	o = msgp.Require(b, z.Msgsize())
	// map header, size 3
	o = append(o, 0x83, 0x83)
	if oTemp, err := z.Role.MarshalHash(); err != nil {
		return nil, err
	} else {
		o = msgp.AppendBytes(o, oTemp)
	}
	o = append(o, 0x83)
	if oTemp, err := z.ID.MarshalHash(); err != nil {
		return nil, err
	} else {
		o = msgp.AppendBytes(o, oTemp)
	}
	o = append(o, 0x83)
	if z.PubKey == nil {
		o = msgp.AppendNil(o)
	} else {
		if oTemp, err := z.PubKey.MarshalHash(); err != nil {
			return nil, err
		} else {
			o = msgp.AppendBytes(o, oTemp)
		}
	}
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Server) Msgsize() (s int) {
	s = 1 + 5 + z.Role.Msgsize() + 3 + z.ID.Msgsize() + 7
	if z.PubKey == nil {
		s += msgp.NilSize
	} else {
		s += z.PubKey.Msgsize()
	}
	return
}

// MarshalHash marshals for hash
func (z ServerState) MarshalHash() (o []byte, err error) {
	var b []byte
	o = msgp.Require(b, z.Msgsize())
	o = msgp.AppendInt(o, int(z))
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z ServerState) Msgsize() (s int) {
	s = msgp.IntSize
	return
}
